# RuboCop configuration for A2A Ruby SDK
# Following a2a-python's ruff configuration patterns

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'coverage/**/*'
    - 'sorbet/**/*'

# Layout and formatting (equivalent to ruff's formatting rules)
Layout/LineLength:
  Max: 120
  AllowedPatterns: 
    - '\A\s*#'  # Allow long comments
    - 'https?://'  # Allow long URLs

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Style rules (following a2a-python conventions)
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Metrics (equivalent to ruff's complexity rules)
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/generators/**/*'
    - '*.gemspec'
    - 'config/routes.rb'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 30

Metrics/ParameterLists:
  Max: 8

# Naming conventions
Naming/FileName:
  Exclude:
    - 'lib/a2a-ruby.rb'

Naming/VariableNumber:
  EnforcedStyle: snake_case

# Performance rules
Performance/StringReplacement:
  Enabled: true

Performance/RedundantBlockCall:
  Enabled: true



# RSpec-specific rules (equivalent to pytest configuration)
RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'
    - 'spec/system/**/*'
    - 'spec/compliance/**/*'
    - 'spec/performance/**/*'

RSpec/FilePath:
  Enabled: false  # Allow flexible file naming

RSpec/SpecFilePathFormat:
  Enabled: false  # Allow flexible file naming

RSpec/ContextWording:
  Enabled: false  # Allow flexible context descriptions

RSpec/DescribedClass:
  Enabled: true

RSpec/InstanceVariable:
  AssignmentOnly: false

RSpec/MultipleDescribes:
  Enabled: false  # Allow multiple describes in test files

RSpec/IdenticalEqualityAssertion:
  Enabled: false  # Allow placeholder tests

RSpec/ExpectActual:
  Enabled: false  # Allow placeholder tests

RSpec/IteratedExpectation:
  Enabled: false  # Allow iterating over arrays in tests

RSpec/MessageSpies:
  Enabled: false  # Allow traditional mocking style

RSpec/VerifiedDoubles:
  Enabled: false  # Allow regular doubles

RSpec/LeakyConstantDeclaration:
  Enabled: false  # Allow constants in test blocks

# Security rules
Security/YAMLLoad:
  Enabled: true

Security/Eval:
  Enabled: true

# Bundler rules
Bundler/OrderedGems:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: true

# Disable problematic cops that are causing errors
Capybara/RSpec/PredicateMatcher:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false