# RuboCop configuration for A2A Ruby gem
# Simple and practical configuration without problematic plugins

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - '.git/**/*'
    - 'spec/**/*'  # Skip all spec files to avoid RSpec plugin issues
    - 'lib/a2a/rails/generators/templates/**/*'  # Skip ERB templates

# Layout and formatting
Layout/LineLength:
  Max: 130  # Allow slightly longer lines for complex expressions
  Exclude:
    - '*.gemspec'

# Style rules - be practical
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Metrics - be realistic for complex gem
Metrics/BlockLength:
  Max: 50
  Exclude:
    - '*.gemspec'
    - 'config/**/*'
    - 'lib/a2a/rails/tasks/**/*'

Metrics/AbcSize:
  Max: 50
  Exclude:
    - 'lib/a2a/transport/**/*'  # Transport layer can be complex
    - 'lib/a2a/protocol/**/*'   # Protocol implementation can be complex

Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'lib/a2a/rails/generators/**/*'

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'lib/a2a/transport/**/*'
    - 'lib/a2a/protocol/**/*'
    - 'lib/a2a/server/**/*'

Metrics/CyclomaticComplexity:
  Max: 20
  Exclude:
    - 'lib/a2a/transport/**/*'
    - 'lib/a2a/protocol/**/*'
    - 'lib/a2a/client/**/*'

Metrics/PerceivedComplexity:
  Max: 20
  Exclude:
    - 'lib/a2a/transport/**/*'
    - 'lib/a2a/protocol/**/*'
    - 'lib/a2a/client/**/*'

Metrics/ModuleLength:
  Max: 300
  Exclude:
    - 'lib/a2a/rails/**/*'  # Rails helpers can be longer

Metrics/ParameterLists:
  Max: 10  # Allow more parameters for complex constructors
  Exclude:
    - 'lib/a2a/types/**/*'  # Type constructors can have many parameters
    - 'lib/a2a/client/**/*'  # Client classes can have many config parameters
    - 'lib/a2a/protocol/**/*'  # Protocol classes can have many parameters

# Naming rules
Naming/FileName:
  Exclude:
    - 'lib/a2a-rails.rb'  # Allow this specific file name

# Gemspec rules
Gemspec/DevelopmentDependencies:
  Enabled: false  # Allow dev dependencies in gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false  # Allow different Ruby version requirements

# Lint rules - be practical
Lint/MissingSuper:
  Enabled: false  # Many classes intentionally don't call super

Lint/DuplicateBranch:
  Enabled: false  # Sometimes duplicate branches are clearer

Lint/DuplicateMethods:
  Enabled: false  # Allow method redefinition in some cases

Lint/IneffectiveAccessModifier:
  Enabled: false  # Allow flexible access modifiers

Lint/HashCompareByIdentity:
  Enabled: false  # Allow object_id as hash keys where needed

# Syntax errors must be fixed manually

# Naming rules - be flexible
Naming/AccessorMethodName:
  Enabled: false  # Allow get_/set_ prefixes

Naming/PredicatePrefix:
  Enabled: false  # Allow has_ prefixes

Naming/PredicateMethod:
  Enabled: false  # Allow validate_ methods

# Style rules - be practical
Style/OptionalBooleanParameter:
  Enabled: false  # Allow boolean default parameters

Style/EmptyElse:
  Enabled: false  # Sometimes empty else is clearer

Style/RedundantCondition:
  Enabled: false  # Sometimes redundant conditions are clearer

# Performance rules removed - require rubocop-performance plugin